apiVersion: apps/v1
kind: Deployment
metadata:
  name: skaffold-hhs-deploy
  namespace: user4
spec:
  replicas: 2
  selector:
    matchLabels:
      run: skaffold-hhs-deploy
  template:
    metadata:
      labels:
        run: skaffold-hhs-deploy
    spec:
      containers:
      - image: rosehs00/skaffold-hhs
        name: test
        ports:
        - containerPort: 80


