apiVersion: v1
kind: Service
metadata:
  name: svc-skaffold-hhs
  namespace: user4
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  type: NodePort
  selector:
    run: skaffold-hhs-deploy

